### ISSUE TITLE
specific usage？

### ISSUE THREAD

**Issue by marksugar** [agile6v/container_cpu_detection#2]
I want to know how it is actually used.
can give a complete example?

**Comment by agile6v** [comment]
Hello

It's actually very simple to use.  You need to clone this repo to the running machine, and then run make && make test. It will print out the result of the test program and also print out the parameter info of the `docker run`. For the description of the related parameters refers to the Usage of the `README`.  Hope that would be useful for you. 

Regards.

**Comment by marksugar** [comment]
@agile6v 
I am following the Makefile
When I set --cpuset-cpus 0,1 --cpu-quota 200000, and mounted

-v `pwd`/detection.so:/usr/lib/detection.so
-v `pwd`/sysconf_test:/tmp/sysconf_test
Environmental variable
-e DETECTION_TARGETS=sysconf_test
-e LD_PRELOAD=/usr/lib/detection.so

It works well

thanks
